# **Section A: Data Structures & Control Structures**

**1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.**

In [2]:
##Create a list of 5 integers
num=[10,20,30,40,50]
print('Original List is:',num)

##append()
num.append(60)
print('After append(60) list is:',num)

##extend
num.extend([70,80])
print('After extend ([60,70]) list is:',num)

##insert()
num.insert(2,25)
print('After inserting 25 list is:',num)

##remove()
num.remove(30)
print('After removing 30 list is:',num)

##pop()
removed_item = num.pop()
print("After pop():", num)
print("Popped Item:", removed_item)

##index()
print('Index of 40 is:',num.index(40))

##count()
print('Count of 50 is:',num.count(50))

##sort
num.sort()
print('Sorted list is',num)

##Reverse()
num.reverse()
print('Reversed list is:',num)

##clear()
num.clear()
print("After clear():", num)

Original List is: [10, 20, 30, 40, 50]
After append(60) list is: [10, 20, 30, 40, 50, 60]
After extend ([60,70]) list is: [10, 20, 30, 40, 50, 60, 70, 80]
After inserting 25 list is: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After removing 30 list is: [10, 20, 25, 40, 50, 60, 70, 80]
After pop(): [10, 20, 25, 40, 50, 60, 70]
Popped Item: 80
Index of 40 is: 3
Count of 50 is: 1
Sorted list is [10, 20, 25, 40, 50, 60, 70]
Reversed list is: [70, 60, 50, 40, 25, 20, 10]
After clear(): []


**2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.**

In [7]:
##creating tuple that stores 3 student names
students=('Arjun','Chandu','David')

##trying to change second name
students[1]='Sneha'
print(students)

TypeError: 'tuple' object does not support item assignment

*Explaination :(Tuple is immutable if we want to change items better use list. When we try to replace the second name ("Chandu") with "Sneha", Python gives a TypeError because tuples do not allow modification of their elements.)*

**3.	Create a set of integers with some duplicate values. Print the set and explain the output**

In [9]:
##creating set with duplicate values
set={10,20,30,10,20,40,50}

print('set',set)

set {50, 20, 40, 10, 30}


*Explaination: The duplicate values 10 and 20 are automatically removed because a set stores only unique elements. Therefore, the set contains only 10, 20, 30, 40, and 50. The order appears as {50, 20, 40, 10, 30} because sets are unordered, so elements may be displayed in a different order each time the program runs.*

**4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.**

In [11]:
##creating dictionary
student={
    'name':'Arjun',
    'age':20,
    'city':'Banglore'
}

##updating age
student['age']=21

##adding new key value
student['email']='arjun12@gmail.com'

##printing final dictionary
print(student)

{'name': 'Arjun', 'age': 21, 'city': 'Banglore', 'email': 'arjun12@gmail.com'}


**5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.**

In [13]:
##Age of the person
age=20

##checking voting eligibilty
if age>=18:
  print('Person eligible for Voting')
else:
  print('person is not eligible for Voting')

Person eligible for Voting


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'
**bold text**

In [16]:
##marks of student
marks=74

##checking grade
if marks>=90:
   print('Grade:A')
elif marks>=75:
   print('Grade:B')
elif marks>=50:
   print('Grade:C')
else:
   print('Grade:Fail')


Grade:C


**7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.**

In [17]:
##Given number
num=39

if num>=0:
  print('Postive number')

  if num%2==0:
    print('Even Number')
  else:
    print('Odd Number')

elif num==0:
  print('Number is zero')

else:
  print('Negative Number')

Postive number
Odd Number


# Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10 **bold text**


In [20]:
import numpy as np

##scalr
scalar=np.array(5)
print('Scalar:')
print(scalar)

##1D array
arr1=np.array([1,2,3,4,5])
print('\n1D array')
print(arr1)

##2D array
arr2=np.array([[10,20,30],[40,50,60]])
print('\n2D array')
print(arr2)

Scalar:
5

1D array
[1 2 3 4 5]

2D array
[[10 20 30]
 [40 50 60]]


**9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().**

In [21]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
arr = np.random.randint(0, 101, size=(4, 4))

print(arr)

[[16 68 18  7]
 [71 28 19 39]
 [12 94 62 42]
 [54 20 13 45]]


**10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.**

In [22]:
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Convert to DataFrame and add column names
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


# Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows **bold text**


In [23]:
import pandas as pd
import numpy as np

# Create DataFrame with 10 rows
data = {
    'Name': ['Asha', 'Rahul', 'Priya', 'Kiran', 'Sneha',
             'Arjun', 'Meena', 'Ravi', 'Pooja', 'Rahul'],
    'Age': [21, 22, 20, 23, 21, 24, 22, 23, 20, 22],
    'City': ['Bangalore', 'Hyderabad', 'Chennai', 'Mumbai', 'Delhi',
             'Pune', 'Kolkata', 'Jaipur', 'Lucknow', 'Hyderabad'],
    'Salary': [30000, 40000, np.nan, 45000, 38000,
               50000, np.nan, 42000, 36000, 40000]
}

df = pd.DataFrame(data)

# 1. Display info
print("DataFrame Info:")
df.info()

# 2. Display description
print("\nDataFrame Description:")
print(df.describe())

# 3. Select Name and City columns
print("\nName and City Columns:")
print(df[['Name', 'City']])

# 4. Drop City column
df = df.drop('City', axis=1)
print("\nAfter Dropping City Column:")
print(df)

# 5. Fill missing Salary values with mean
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
print("\nAfter Filling Missing Salary Values:")
print(df)

# 6. Remove duplicate rows
df = df.drop_duplicates()
print("\nAfter Removing Duplicate Rows:")
print(df)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

DataFrame Description:
             Age        Salary
count  10.000000      8.000000
mean   21.800000  40125.000000
std     1.316561   5962.681564
min    20.000000  30000.000000
25%    21.000000  37500.000000
50%    22.000000  40000.000000
75%    22.750000  42750.000000
max    24.000000  50000.000000

Name and City Columns:
    Name       City
0   Asha  Bangalore
1  Rahul  Hyderabad
2  Priya    Chennai
3  Kiran     Mumbai
4  Sneha      Delhi
5  Arjun       Pune
6  Meena    Kolkata
7   Ravi     Jaipur
8  Pooja    Lucknow
9  Rahul  Hyderabad

After Dropping City Column:
    Name  Age   Sa